version: "3.0"
services:
  zookeeper:
    restart: always
    image: "zookeeper:3.5"
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;zookeeper:2181
  kafka:
    restart: always
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INSIDE://:9093,OUTSIDE://:9092
      KAFKA_ADVERTISED_LISTENERS: INSIDE://:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "172.17.0.1:6491:9090"
      - "1893:1883"
      - "172.17.0.1:7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: kafka
      TB_KAFKA_SERVERS: kafka:9092
      SSL_ENABLED: "true"
      SSL_CREDENTIALS_TYPE: PEM
      SSL_PEM_CERT: server.pem
      SSL_PEM_KEY: server_key.pem
      # MQTT_SSL_ENABLED: "true"
      # MQTT_SSL_CREDENTIALS_TYPE: PEM
      # MQTT_SSL_PEM_CERT: server.pem
      # MQTT_SSL_PEM_KEY: server_key.pem
    volumes:
      - ./mytb-data:/data
      - ./mytb-logs:/var/log/thingsboard
      - /root/.acme.sh/vm.elestio.app/fullchain.cer:/etc/thingsboard/conf/server.pem
      - /root/.acme.sh/vm.elestio.app/vm.elestio.app.key:/etc/thingsboard/conf/server_key.pem
